### ISSUE TITLE
Error in filename, caused to not working gulp

### ISSUE THREAD

**Issue by siberianbear** [frontcraft/fronthack#50]
I've made freshly "installation" of Fronthack in LinuxLite machine.
Everything was successful, till a running of gulp.
At start of gulp I've got a message
[07:20:43] Finished 'mustache' after 199 ms
Styleguide generation failed
Error: Error: ENOENT: no such file or directory, open '/home/adminuser/developing/fronthack/sass/components/html/!EXAMPLE.html' in /home/adminuser/developing/fronthack/sass/components/!EXAMPLE.sass
[07:20:45] Finished 'styleguide:applystyles' after 2.31 s

Then I've found the reason of the error: a register of filename.
In your configuration filename is "!EXAMPLE.html", but originally in filesystem soon after install, it's "!example.html", so it's matter for linux/macos machines.

Need to rename it in filesystem, or in configuration and issue will be solved.

**Comment by frontcraft** [comment]
It did not make difference on MacOS. It looks like LinuxLite is more sensitive there. I renamed the !example.html file to uppercase. @siberianbear can you check if recent version of Fronthack now works for you out of the box?

**Comment by frontcraft** [comment]
Checked on Linux system
